name: Docker Image CI&CD

on:
  push:
    branches: [ "main" ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login
      run:
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - name: Build the Docker image
      run: docker build . -t registry.heroku.com/$APP_NAME/web

    - name: Push to Heroku
      run: heroku container:push web -a $APP_NAME
    - name: Release
      run: heroku container:release web -a $APP_NAME